package il.ac.bgu.cs.fvm.tests;

import static org.junit.Assert.assertEquals;

import java.util.Arrays;
import java.util.HashSet;

import org.junit.Test;

import il.ac.bgu.cs.fvm.Exercise4FacadeImplementation;
import il.ac.bgu.cs.fvm.automata.Automaton;
import il.ac.bgu.cs.fvm.labels.State;
import il.ac.bgu.cs.fvm.ltl.AtomicProposition;
import il.ac.bgu.cs.fvm.ltl.Ltl;
import il.ac.bgu.cs.fvm.ltl.Until;

public class LTLTest3 {

	Exercise4FacadeImplementation fvmFacadeImpl = new Exercise4FacadeImplementation();

	@Test
	public void test() {
		AtomicProposition p = new AtomicProposition("p");
		AtomicProposition q = new AtomicProposition("q");
		AtomicProposition s = new AtomicProposition("s");

		Ltl ltl = new Until(p, new Until(q, s));

		Automaton aut = fvmFacadeImpl.LTL2BA(ltl);
		System.out.println(aut.getAcceptingStates().size());
		System.out.println(expected().getAcceptingStates().size());
		
		
		System.out.println(aut.getTransitions().size());
		System.out.println(expected().getTransitions().size());

		
		assertEquals(aut, expected());
	}

	Automaton expected() {
		Automaton aut = new Automaton();
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, !s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, !s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q")), new State("[s, (p U (q U s)), (q U s), !p, !q],1"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q")), new State("[s, (p U (q U s)), (q U s), p, !q],1"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q")), new State("[s, (p U (q U s)), (q U s), !p, !q],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, !s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, !s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q")), new State("[s, (p U (q U s)), (q U s), p, !q],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q")), new State("[s, (p U (q U s)), (q U s), !p, !q],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, !s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, !s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q")), new State("[s, (p U (q U s)), (q U s), p, !q],2"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],0"), new HashSet<String>(Arrays.asList("p")), new State("[q, !s, !(q U s), (p U (q U s)), p],1"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],0"), new HashSet<String>(Arrays.asList("p")), new State("[q, !s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],0"), new HashSet<String>(Arrays.asList("p")), new State("[q, s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],0"), new HashSet<String>(Arrays.asList("p")), new State("[q, s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],0"), new HashSet<String>(Arrays.asList("p")), new State("[q, !s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],0"), new HashSet<String>(Arrays.asList("p")), new State("[!s, !(q U s), (p U (q U s)), p, !q],1"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],0"), new HashSet<String>(Arrays.asList("p")), new State("[s, (p U (q U s)), (q U s), !p, !q],1"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],0"), new HashSet<String>(Arrays.asList("p")), new State("[s, (p U (q U s)), (q U s), p, !q],1"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],1"), new HashSet<String>(Arrays.asList("p")), new State("[q, !s, !(q U s), (p U (q U s)), p],1"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],1"), new HashSet<String>(Arrays.asList("p")), new State("[q, !s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],1"), new HashSet<String>(Arrays.asList("p")), new State("[q, s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],1"), new HashSet<String>(Arrays.asList("p")), new State("[q, s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],1"), new HashSet<String>(Arrays.asList("p")), new State("[q, !s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],1"), new HashSet<String>(Arrays.asList("p")), new State("[!s, !(q U s), (p U (q U s)), p, !q],1"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],1"), new HashSet<String>(Arrays.asList("p")), new State("[s, (p U (q U s)), (q U s), !p, !q],1"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],1"), new HashSet<String>(Arrays.asList("p")), new State("[s, (p U (q U s)), (q U s), p, !q],1"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],2"), new HashSet<String>(Arrays.asList("p")), new State("[q, !s, !(q U s), (p U (q U s)), p],0"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],2"), new HashSet<String>(Arrays.asList("p")), new State("[q, !s, (p U (q U s)), (q U s), !p],0"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],2"), new HashSet<String>(Arrays.asList("p")), new State("[q, !s, (p U (q U s)), (q U s), p],0"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],2"), new HashSet<String>(Arrays.asList("p")), new State("[q, s, (p U (q U s)), (q U s), !p],0"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],2"), new HashSet<String>(Arrays.asList("p")), new State("[q, s, (p U (q U s)), (q U s), p],0"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],2"), new HashSet<String>(Arrays.asList("p")), new State("[!s, !(q U s), (p U (q U s)), p, !q],0"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],2"), new HashSet<String>(Arrays.asList("p")), new State("[s, (p U (q U s)), (q U s), !p, !q],0"));
		aut.addTransition(new State("[!s, !(q U s), (p U (q U s)), p, !q],2"), new HashSet<String>(Arrays.asList("p")), new State("[s, (p U (q U s)), (q U s), p, !q],0"));
		aut.addTransition(new State("[q, !s, !(q U s), (p U (q U s)), p],2"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, !s, !(q U s), (p U (q U s)), p],0"));
		aut.addTransition(new State("[q, !s, !(q U s), (p U (q U s)), p],2"), new HashSet<String>(Arrays.asList("p", "q")), new State("[!s, !(q U s), (p U (q U s)), p, !q],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],0"), new HashSet<String>(Arrays.asList("p", "s")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],0"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, !s, !(q U s), (p U (q U s)), p],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],0"), new HashSet<String>(Arrays.asList("p", "s")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],0"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), p],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],0"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, !s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],0"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],0"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],0"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, !s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],0"), new HashSet<String>(Arrays.asList("p", "s")), new State("[!s, !(q U s), (p U (q U s)), p, !q],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],0"), new HashSet<String>(Arrays.asList("p", "s")), new State("[s, (p U (q U s)), (q U s), !p, !q],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],0"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],0"), new HashSet<String>(Arrays.asList("p", "s")), new State("[s, (p U (q U s)), (q U s), p, !q],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],1"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],1"), new HashSet<String>(Arrays.asList("p", "s")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],1"), new HashSet<String>(Arrays.asList("p", "s")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],1"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), p],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],1"), new HashSet<String>(Arrays.asList("p", "s")), new State("[s, (p U (q U s)), (q U s), !p, !q],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],1"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, !s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],1"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],1"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, !s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],1"), new HashSet<String>(Arrays.asList("p", "s")), new State("[!s, !(q U s), (p U (q U s)), p, !q],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],1"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, !s, !(q U s), (p U (q U s)), p],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],1"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],1"), new HashSet<String>(Arrays.asList("p", "s")), new State("[s, (p U (q U s)), (q U s), p, !q],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],2"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, !s, !(q U s), (p U (q U s)), p],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],2"), new HashSet<String>(Arrays.asList("p", "s")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],2"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), p],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],2"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, !s, (p U (q U s)), (q U s), !p],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],2"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, !s, (p U (q U s)), (q U s), p],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],2"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, s, (p U (q U s)), (q U s), !p],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],2"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, s, (p U (q U s)), (q U s), p],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],2"), new HashSet<String>(Arrays.asList("p", "s")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],2"), new HashSet<String>(Arrays.asList("p", "s")), new State("[!s, !(q U s), (p U (q U s)), p, !q],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],2"), new HashSet<String>(Arrays.asList("p", "s")), new State("[s, (p U (q U s)), (q U s), !p, !q],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],2"), new HashSet<String>(Arrays.asList("p", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), p, !q],2"), new HashSet<String>(Arrays.asList("p", "s")), new State("[s, (p U (q U s)), (q U s), p, !q],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, !s, !(q U s), (p U (q U s)), p],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), p],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, !s, (p U (q U s)), (q U s), !p],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, !s, (p U (q U s)), (q U s), p],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, s, (p U (q U s)), (q U s), !p],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, s, (p U (q U s)), (q U s), p],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[!s, !(q U s), (p U (q U s)), p, !q],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[s, (p U (q U s)), (q U s), !p, !q],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[s, (p U (q U s)), (q U s), p, !q],0"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q")), new State("[q, !s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q")), new State("[q, s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q")), new State("[q, s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q")), new State("[q, !s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q")), new State("[s, (p U (q U s)), (q U s), !p, !q],1"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q")), new State("[s, (p U (q U s)), (q U s), p, !q],1"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q")), new State("[q, s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q")), new State("[s, (p U (q U s)), (q U s), !p, !q],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q")), new State("[q, !s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q")), new State("[q, s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q")), new State("[q, !s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q")), new State("[s, (p U (q U s)), (q U s), p, !q],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q", "s")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, !s, !(q U s), (p U (q U s)), p],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q", "s")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), p],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, !s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, !s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q", "s")), new State("[!s, !(q U s), (p U (q U s)), p, !q],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q", "s")), new State("[s, (p U (q U s)), (q U s), !p, !q],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],0"), new HashSet<String>(Arrays.asList("q", "s")), new State("[s, (p U (q U s)), (q U s), p, !q],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],2"), new HashSet<String>(Arrays.asList("s")), new State("[q, !s, !(q U s), (p U (q U s)), p],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],2"), new HashSet<String>(Arrays.asList("s")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],2"), new HashSet<String>(Arrays.asList("s")), new State("[q, !s, !(p U (q U s)), !(q U s), p],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],2"), new HashSet<String>(Arrays.asList("s")), new State("[q, !s, (p U (q U s)), (q U s), !p],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],2"), new HashSet<String>(Arrays.asList("s")), new State("[q, !s, (p U (q U s)), (q U s), p],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],2"), new HashSet<String>(Arrays.asList("s")), new State("[q, s, (p U (q U s)), (q U s), !p],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],2"), new HashSet<String>(Arrays.asList("s")), new State("[q, s, (p U (q U s)), (q U s), p],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],2"), new HashSet<String>(Arrays.asList("s")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],2"), new HashSet<String>(Arrays.asList("s")), new State("[!s, !(q U s), (p U (q U s)), p, !q],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],2"), new HashSet<String>(Arrays.asList("s")), new State("[s, (p U (q U s)), (q U s), !p, !q],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],2"), new HashSet<String>(Arrays.asList("s")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],0"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],2"), new HashSet<String>(Arrays.asList("s")), new State("[s, (p U (q U s)), (q U s), p, !q],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q", "s")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q", "s")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), p],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q", "s")), new State("[s, (p U (q U s)), (q U s), !p, !q],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, !s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, !s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q", "s")), new State("[!s, !(q U s), (p U (q U s)), p, !q],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, !s, !(q U s), (p U (q U s)), p],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],1"), new HashSet<String>(Arrays.asList("q", "s")), new State("[s, (p U (q U s)), (q U s), p, !q],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, !s, !(q U s), (p U (q U s)), p],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), p],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, !s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, !s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[!s, !(q U s), (p U (q U s)), p, !q],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[s, (p U (q U s)), (q U s), !p, !q],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[s, (p U (q U s)), (q U s), p, !q],1"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), p],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[s, (p U (q U s)), (q U s), !p, !q],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, !s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, !s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[!s, !(q U s), (p U (q U s)), p, !q],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, !s, !(q U s), (p U (q U s)), p],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q", "s")), new State("[s, (p U (q U s)), (q U s), p, !q],2"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, !s, !(q U s), (p U (q U s)), p],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q", "s")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), p],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, !s, (p U (q U s)), (q U s), !p],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, !s, (p U (q U s)), (q U s), p],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, s, (p U (q U s)), (q U s), !p],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, s, (p U (q U s)), (q U s), p],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q", "s")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q", "s")), new State("[!s, !(q U s), (p U (q U s)), p, !q],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q", "s")), new State("[s, (p U (q U s)), (q U s), !p, !q],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q", "s")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],0"));
		aut.addTransition(new State("[q, s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q", "s")), new State("[s, (p U (q U s)), (q U s), p, !q],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"), new HashSet<String>(), new State("[q, s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"), new HashSet<String>(), new State("[!s, !(p U (q U s)), !(q U s), p, !q],2"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"), new HashSet<String>(), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"), new HashSet<String>(), new State("[q, !s, !(p U (q U s)), !(q U s), p],2"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"), new HashSet<String>(), new State("[s, (p U (q U s)), (q U s), !p, !q],2"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"), new HashSet<String>(), new State("[q, !s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"), new HashSet<String>(), new State("[q, s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"), new HashSet<String>(), new State("[q, !s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"), new HashSet<String>(), new State("[!s, !(q U s), (p U (q U s)), p, !q],2"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"), new HashSet<String>(), new State("[q, !s, !(q U s), (p U (q U s)), p],2"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"), new HashSet<String>(), new State("[q, !s, !(p U (q U s)), !(q U s), !p],2"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"), new HashSet<String>(), new State("[s, (p U (q U s)), (q U s), p, !q],2"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"), new HashSet<String>(), new State("[q, !s, !(q U s), (p U (q U s)), p],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"), new HashSet<String>(), new State("[!s, !(p U (q U s)), !(q U s), p, !q],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"), new HashSet<String>(), new State("[q, !s, !(p U (q U s)), !(q U s), p],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"), new HashSet<String>(), new State("[q, !s, (p U (q U s)), (q U s), !p],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"), new HashSet<String>(), new State("[q, !s, (p U (q U s)), (q U s), p],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"), new HashSet<String>(), new State("[q, s, (p U (q U s)), (q U s), !p],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"), new HashSet<String>(), new State("[q, s, (p U (q U s)), (q U s), p],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"), new HashSet<String>(), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"), new HashSet<String>(), new State("[!s, !(q U s), (p U (q U s)), p, !q],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"), new HashSet<String>(), new State("[s, (p U (q U s)), (q U s), !p, !q],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"), new HashSet<String>(), new State("[q, !s, !(p U (q U s)), !(q U s), !p],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"), new HashSet<String>(), new State("[s, (p U (q U s)), (q U s), p, !q],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"), new HashSet<String>(), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"), new HashSet<String>(), new State("[q, !s, !(q U s), (p U (q U s)), p],1"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"), new HashSet<String>(), new State("[!s, !(p U (q U s)), !(q U s), p, !q],1"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"), new HashSet<String>(), new State("[q, !s, !(p U (q U s)), !(q U s), p],1"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"), new HashSet<String>(), new State("[q, !s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"), new HashSet<String>(), new State("[q, s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"), new HashSet<String>(), new State("[q, s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"), new HashSet<String>(), new State("[q, !s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"), new HashSet<String>(), new State("[!s, !(q U s), (p U (q U s)), p, !q],1"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"), new HashSet<String>(), new State("[s, (p U (q U s)), (q U s), !p, !q],1"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"), new HashSet<String>(), new State("[q, !s, !(p U (q U s)), !(q U s), !p],1"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"), new HashSet<String>(), new State("[s, (p U (q U s)), (q U s), p, !q],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],1"), new HashSet<String>(Arrays.asList("s")), new State("[q, s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],1"), new HashSet<String>(Arrays.asList("s")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],1"), new HashSet<String>(Arrays.asList("s")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],1"), new HashSet<String>(Arrays.asList("s")), new State("[q, !s, !(p U (q U s)), !(q U s), p],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],1"), new HashSet<String>(Arrays.asList("s")), new State("[s, (p U (q U s)), (q U s), !p, !q],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],1"), new HashSet<String>(Arrays.asList("s")), new State("[q, !s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],1"), new HashSet<String>(Arrays.asList("s")), new State("[q, s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],1"), new HashSet<String>(Arrays.asList("s")), new State("[q, !s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],1"), new HashSet<String>(Arrays.asList("s")), new State("[!s, !(q U s), (p U (q U s)), p, !q],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],1"), new HashSet<String>(Arrays.asList("s")), new State("[q, !s, !(q U s), (p U (q U s)), p],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],1"), new HashSet<String>(Arrays.asList("s")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],1"), new HashSet<String>(Arrays.asList("s")), new State("[s, (p U (q U s)), (q U s), p, !q],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q")), new State("[q, s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q")), new State("[s, (p U (q U s)), (q U s), !p, !q],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q")), new State("[q, !s, (p U (q U s)), (q U s), p],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q")), new State("[q, s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q")), new State("[q, !s, (p U (q U s)), (q U s), !p],2"));
		aut.addTransition(new State("[q, !s, (p U (q U s)), (q U s), !p],2"), new HashSet<String>(Arrays.asList("q")), new State("[s, (p U (q U s)), (q U s), p, !q],2"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],0"), new HashSet<String>(Arrays.asList("s")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],0"), new HashSet<String>(Arrays.asList("s")), new State("[q, !s, !(q U s), (p U (q U s)), p],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],0"), new HashSet<String>(Arrays.asList("s")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],0"), new HashSet<String>(Arrays.asList("s")), new State("[q, !s, !(p U (q U s)), !(q U s), p],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],0"), new HashSet<String>(Arrays.asList("s")), new State("[q, !s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],0"), new HashSet<String>(Arrays.asList("s")), new State("[q, s, (p U (q U s)), (q U s), !p],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],0"), new HashSet<String>(Arrays.asList("s")), new State("[q, s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],0"), new HashSet<String>(Arrays.asList("s")), new State("[q, !s, (p U (q U s)), (q U s), p],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],0"), new HashSet<String>(Arrays.asList("s")), new State("[!s, !(q U s), (p U (q U s)), p, !q],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],0"), new HashSet<String>(Arrays.asList("s")), new State("[s, (p U (q U s)), (q U s), !p, !q],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],0"), new HashSet<String>(Arrays.asList("s")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],1"));
		aut.addTransition(new State("[s, (p U (q U s)), (q U s), !p, !q],0"), new HashSet<String>(Arrays.asList("s")), new State("[s, (p U (q U s)), (q U s), p, !q],1"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],0"), new HashSet<String>(Arrays.asList("q")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],0"), new HashSet<String>(Arrays.asList("q")), new State("[q, !s, !(q U s), (p U (q U s)), p],1"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],0"), new HashSet<String>(Arrays.asList("q")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],1"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],0"), new HashSet<String>(Arrays.asList("q")), new State("[q, !s, !(p U (q U s)), !(q U s), p],1"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],0"), new HashSet<String>(Arrays.asList("q")), new State("[!s, !(q U s), (p U (q U s)), p, !q],1"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],0"), new HashSet<String>(Arrays.asList("q")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],1"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],1"), new HashSet<String>(Arrays.asList("q")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],2"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],1"), new HashSet<String>(Arrays.asList("q")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],1"), new HashSet<String>(Arrays.asList("q")), new State("[q, !s, !(p U (q U s)), !(q U s), p],2"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],1"), new HashSet<String>(Arrays.asList("q")), new State("[!s, !(q U s), (p U (q U s)), p, !q],2"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],1"), new HashSet<String>(Arrays.asList("q")), new State("[q, !s, !(q U s), (p U (q U s)), p],2"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],1"), new HashSet<String>(Arrays.asList("q")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],2"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],2"), new HashSet<String>(Arrays.asList("q")), new State("[q, !s, !(q U s), (p U (q U s)), p],0"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],2"), new HashSet<String>(Arrays.asList("q")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],0"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],2"), new HashSet<String>(Arrays.asList("q")), new State("[q, !s, !(p U (q U s)), !(q U s), p],0"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],2"), new HashSet<String>(Arrays.asList("q")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],2"), new HashSet<String>(Arrays.asList("q")), new State("[!s, !(q U s), (p U (q U s)), p, !q],0"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), !p],2"), new HashSet<String>(Arrays.asList("q")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), p, !q],2"), new HashSet<String>(Arrays.asList("p")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), p, !q],2"), new HashSet<String>(Arrays.asList("p")), new State("[q, !s, !(p U (q U s)), !(q U s), p],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), p, !q],2"), new HashSet<String>(Arrays.asList("p")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), p, !q],2"), new HashSet<String>(Arrays.asList("p")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],0"));
		aut.addTransition(new State("[q, !s, !(q U s), (p U (q U s)), p],0"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, !s, !(q U s), (p U (q U s)), p],1"));
		aut.addTransition(new State("[q, !s, !(q U s), (p U (q U s)), p],0"), new HashSet<String>(Arrays.asList("p", "q")), new State("[!s, !(q U s), (p U (q U s)), p, !q],1"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), p, !q],0"), new HashSet<String>(Arrays.asList("p")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), p, !q],0"), new HashSet<String>(Arrays.asList("p")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],1"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), p, !q],0"), new HashSet<String>(Arrays.asList("p")), new State("[q, !s, !(p U (q U s)), !(q U s), p],1"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), p, !q],0"), new HashSet<String>(Arrays.asList("p")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],1"));
		aut.addTransition(new State("[q, !s, !(q U s), (p U (q U s)), p],1"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, !s, !(q U s), (p U (q U s)), p],1"));
		aut.addTransition(new State("[q, !s, !(q U s), (p U (q U s)), p],1"), new HashSet<String>(Arrays.asList("p", "q")), new State("[!s, !(q U s), (p U (q U s)), p, !q],1"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), p, !q],1"), new HashSet<String>(Arrays.asList("p")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],2"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), p, !q],1"), new HashSet<String>(Arrays.asList("p")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), p, !q],1"), new HashSet<String>(Arrays.asList("p")), new State("[q, !s, !(p U (q U s)), !(q U s), p],2"));
		aut.addTransition(new State("[!s, !(p U (q U s)), !(q U s), p, !q],1"), new HashSet<String>(Arrays.asList("p")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],2"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],1"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],1"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, !s, !(p U (q U s)), !(q U s), p],1"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), p],0"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],1"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],2"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],2"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, !s, !(p U (q U s)), !(q U s), p],2"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), p],1"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],2"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q")), new State("[!s, !(p U (q U s)), !(q U s), p, !q],0"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, !s, !(p U (q U s)), !(q U s), p],0"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q")), new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"));
		aut.addTransition(new State("[q, !s, !(p U (q U s)), !(q U s), p],2"), new HashSet<String>(Arrays.asList("p", "q")), new State("[q, !s, !(p U (q U s)), !(q U s), !p],0"));
		aut.setInitial(new State("[q, !s, !(q U s), (p U (q U s)), p],0"));
		aut.setInitial(new State("[q, !s, (p U (q U s)), (q U s), !p],0"));
		aut.setInitial(new State("[q, !s, (p U (q U s)), (q U s), p],0"));
		aut.setInitial(new State("[q, s, (p U (q U s)), (q U s), !p],0"));
		aut.setInitial(new State("[q, s, (p U (q U s)), (q U s), p],0"));
		aut.setInitial(new State("[!s, !(q U s), (p U (q U s)), p, !q],0"));
		aut.setInitial(new State("[s, (p U (q U s)), (q U s), !p, !q],0"));
		aut.setInitial(new State("[s, (p U (q U s)), (q U s), p, !q],0"));
		aut.setAccepting(new State("[q, !s, !(q U s), (p U (q U s)), p],0"));
		aut.setAccepting(new State("[!s, !(p U (q U s)), !(q U s), p, !q],0"));
		aut.setAccepting(new State("[q, !s, !(p U (q U s)), !(q U s), p],0"));
		aut.setAccepting(new State("[q, !s, (p U (q U s)), (q U s), !p],0"));
		aut.setAccepting(new State("[q, !s, (p U (q U s)), (q U s), p],0"));
		aut.setAccepting(new State("[q, s, (p U (q U s)), (q U s), !p],0"));
		aut.setAccepting(new State("[q, s, (p U (q U s)), (q U s), p],0"));
		aut.setAccepting(new State("[!s, !(p U (q U s)), !(q U s), !p, !q],0"));
		aut.setAccepting(new State("[!s, !(q U s), (p U (q U s)), p, !q],0"));
		aut.setAccepting(new State("[s, (p U (q U s)), (q U s), !p, !q],0"));
		aut.setAccepting(new State("[q, !s, !(p U (q U s)), !(q U s), !p],0"));
		aut.setAccepting(new State("[s, (p U (q U s)), (q U s), p, !q],0"));
		return aut;

	}

}
